// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefineryBooking.Data;

#nullable disable

namespace RefineryBooking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260725185604_EnhanceBookingFields")]
    partial class EnhanceBookingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            ConcurrencyStamp = "928aa44a-8b3c-46d5-b320-a82da19e3692",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            ConcurrencyStamp = "83989ce9-be91-4ccf-900d-67450c3d5c3e",
                            Name = "Allocator",
                            NormalizedName = "ALLOCATOR"
                        },
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            ConcurrencyStamp = "27b8d3a0-6089-4cd0-95a7-0d84818d0e5b",
                            Name = "ITFM",
                            NormalizedName = "ITFM"
                        },
                        new
                        {
                            Id = "44444444-4444-4444-4444-444444444444",
                            ConcurrencyStamp = "5ecb3fcc-85f9-4a12-bea9-9e36c4b21cc9",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "aaaa-aaaa-aaaa-aaaa",
                            RoleId = "11111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            UserId = "bbbb-bbbb-bbbb-bbbb",
                            RoleId = "22222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            UserId = "cccc-cccc-cccc-cccc",
                            RoleId = "33333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            UserId = "dddd-dddd-dddd-dddd",
                            RoleId = "44444444-4444-4444-4444-444444444444"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RefineryBooking.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeBadgeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "aaaa-aaaa-aaaa-aaaa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df81668a-5c5a-478b-8182-38d10bf93841",
                            Department = "IT Operations",
                            Email = "admin@refinery.com",
                            EmailConfirmed = true,
                            EmployeeBadgeId = "REF-001",
                            FullName = "System Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@REFINERY.COM",
                            NormalizedUserName = "ADMIN@REFINERY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHeWJtqUIGnNzRFBvaRJnFgsfM5Vyk1F/mTi994wImpNc/EeAYCj41MZnN63G5Rwig==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9b2216ce-b661-41bc-86a8-10ef711ad420",
                            TwoFactorEnabled = false,
                            UserName = "admin@refinery.com"
                        },
                        new
                        {
                            Id = "bbbb-bbbb-bbbb-bbbb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2c21156f-c820-47f8-8f0c-c44d460a6c8d",
                            Department = "Facility Scheduling",
                            Email = "allocator@refinery.com",
                            EmailConfirmed = true,
                            EmployeeBadgeId = "REF-042",
                            FullName = "Sarah Jenkins (Logistics)",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALLOCATOR@REFINERY.COM",
                            NormalizedUserName = "ALLOCATOR@REFINERY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFKCxTKyHLLaUAsVtiHc4s6SoFa9AwdU27/hAhP/foRevZ1EHDF0BVputMLH2tuu1Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "14e79640-72ba-42e2-9562-924a4ce0ca97",
                            TwoFactorEnabled = false,
                            UserName = "allocator@refinery.com"
                        },
                        new
                        {
                            Id = "cccc-cccc-cccc-cccc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "78a086d1-87b2-4d1e-963a-0d90ae6039f8",
                            Department = "IT & Facilities",
                            Email = "itfm@refinery.com",
                            EmailConfirmed = true,
                            EmployeeBadgeId = "REF-108",
                            FullName = "Marcus Vance (AV Lead)",
                            LockoutEnabled = false,
                            NormalizedEmail = "ITFM@REFINERY.COM",
                            NormalizedUserName = "ITFM@REFINERY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDDy/2qNUyoJgaPeNgvJa6S+oXrcwMvmvLXzpi7YVaQa9l12yMXFxylL2LVyXVMVBg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7c809da6-1ef8-4c95-be0f-1dbc09395733",
                            TwoFactorEnabled = false,
                            UserName = "itfm@refinery.com"
                        },
                        new
                        {
                            Id = "dddd-dddd-dddd-dddd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8874bca6-51a2-412f-b1bf-449358849a1b",
                            Department = "Catalytic Cracking Unit",
                            Email = "user@refinery.com",
                            EmailConfirmed = true,
                            EmployeeBadgeId = "REF-504",
                            FullName = "Dave Miller (Engineer)",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@REFINERY.COM",
                            NormalizedUserName = "USER@REFINERY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC5eQy3h5B10C4S37onMEWPxZF6cYfC+7kL16+M+e17MpCdn1vS8Khw2kNnSy75DUQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dfc8860d-3df7-4243-85f0-34b726361795",
                            TwoFactorEnabled = false,
                            UserName = "user@refinery.com"
                        });
                });

            modelBuilder.Entity("RefineryBooking.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RefineryBooking.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ConferenceRoomId")
                        .HasColumnType("int");

                    b.Property<string>("CostCentre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpectedAttendees")
                        .HasColumnType("int");

                    b.Property<string>("MeetingTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("RequiresCatering")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ConferenceRoomId", "StartTime", "EndTime", "Status");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RefineryBooking.Models.ConferenceRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("bit");

                    b.Property<bool>("HasVideoConferencing")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWhiteboard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ConferenceRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingLocation = "Admin Block A, Floor 3",
                            Capacity = 24,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "North Gate Boardroom"
                        },
                        new
                        {
                            Id = 2,
                            BuildingLocation = "Plant 2 Operations Center",
                            Capacity = 12,
                            HasProjector = true,
                            HasVideoConferencing = false,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Catalytic Cracker Briefing Room"
                        },
                        new
                        {
                            Id = 3,
                            BuildingLocation = "Visitor Center, Ground Floor",
                            Capacity = 60,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Safety & HAZMAT Training Hall"
                        },
                        new
                        {
                            Id = 4,
                            BuildingLocation = "Technical Services Bldg",
                            Capacity = 8,
                            HasProjector = false,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Pipeline Engineering Hub"
                        },
                        new
                        {
                            Id = 5,
                            BuildingLocation = "HQ Tower, Floor 5",
                            Capacity = 16,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Executive Strategy Suite"
                        },
                        new
                        {
                            Id = 6,
                            BuildingLocation = "Central Control Building",
                            Capacity = 30,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Refinery Operations War Room"
                        },
                        new
                        {
                            Id = 7,
                            BuildingLocation = "Safety Block, Ground Floor",
                            Capacity = 120,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = false,
                            IsActive = true,
                            Name = "HSE Training Auditorium"
                        },
                        new
                        {
                            Id = 8,
                            BuildingLocation = "Maintenance Bldg, Floor 1",
                            Capacity = 20,
                            HasProjector = true,
                            HasVideoConferencing = false,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Turnaround Planning Room"
                        },
                        new
                        {
                            Id = 9,
                            BuildingLocation = "IT Services Block",
                            Capacity = 10,
                            HasProjector = false,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "IT & Instrumentation Lab"
                        },
                        new
                        {
                            Id = 10,
                            BuildingLocation = "Warehouse Block B, Floor 2",
                            Capacity = 14,
                            HasProjector = true,
                            HasVideoConferencing = false,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Logistics & Dispatch Conference Room"
                        });
                });

            modelBuilder.Entity("RefineryBooking.Models.ITFacilityRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("MicCount")
                        .HasColumnType("int");

                    b.Property<bool>("NeedsLaptop")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsLaserPointer")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsPASystem")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsProjector")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsVideoConferencing")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsWhiteboard")
                        .HasColumnType("bit");

                    b.Property<int>("SetupStatus")
                        .HasColumnType("int");

                    b.Property<string>("TechNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("ITFacilityRequirements");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RefineryBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RefineryBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RefineryBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RefineryBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RefineryBooking.Models.Booking", b =>
                {
                    b.HasOne("RefineryBooking.Models.ConferenceRoom", "ConferenceRoom")
                        .WithMany("Bookings")
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RefineryBooking.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RefineryBooking.Models.ITFacilityRequirement", b =>
                {
                    b.HasOne("RefineryBooking.Models.Booking", "Booking")
                        .WithOne("ITRequirement")
                        .HasForeignKey("RefineryBooking.Models.ITFacilityRequirement", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("RefineryBooking.Models.Booking", b =>
                {
                    b.Navigation("ITRequirement");
                });

            modelBuilder.Entity("RefineryBooking.Models.ConferenceRoom", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
