// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefineryBooking.Data;

#nullable disable

namespace RefineryBooking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729154522_HallSpecificAllocators")]
    partial class HallSpecificAllocators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            ConcurrencyStamp = "d16813a1-7755-4d13-95e7-6c93afe1bc06",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            ConcurrencyStamp = "9c71bd2f-d8cb-4f56-a28c-922a68107c66",
                            Name = "Allocator",
                            NormalizedName = "ALLOCATOR"
                        },
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            ConcurrencyStamp = "83260c85-3f35-4134-91bf-f46fcffd2f06",
                            Name = "ITFM",
                            NormalizedName = "ITFM"
                        },
                        new
                        {
                            Id = "44444444-4444-4444-4444-444444444444",
                            ConcurrencyStamp = "f34a9b08-4aad-4887-8b9a-ff8b7673c7f2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "aaaa-aaaa-aaaa-aaaa",
                            RoleId = "11111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            UserId = "bbbb-bbbb-bbbb-bbbb",
                            RoleId = "22222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            UserId = "cccc-cccc-cccc-cccc",
                            RoleId = "33333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            UserId = "dddd-dddd-dddd-dddd",
                            RoleId = "44444444-4444-4444-4444-444444444444"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RefineryBooking.Models.AllocatorHallAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConferenceRoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceRoomId");

                    b.HasIndex("AllocatorUserId", "ConferenceRoomId")
                        .IsUnique();

                    b.ToTable("AllocatorHallAssignments");
                });

            modelBuilder.Entity("RefineryBooking.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeBadgeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "aaaa-aaaa-aaaa-aaaa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "096cd762-252f-4bd2-b201-55a9da0e1e8c",
                            Department = "IT Operations",
                            Email = "admin@nrl.co.in",
                            EmailConfirmed = true,
                            EmployeeBadgeId = "NRL-ADM-001",
                            FullName = "System Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@NRL.CO.IN",
                            NormalizedUserName = "SYS.ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEMS/UG/awBxriw03kqbmPzdeq9ry8gfNMozhCtYn8yJRfsawGaCbDkdRAdRx4Q6HtA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8599b31b-e4ed-433a-bb8c-7e5adea8718f",
                            TwoFactorEnabled = false,
                            UserName = "sys.admin"
                        },
                        new
                        {
                            Id = "bbbb-bbbb-bbbb-bbbb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "71f69e20-a188-4bef-89b6-5020c0268690",
                            Department = "Facility Scheduling",
                            Email = "sarah.jenkins@nrl.co.in",
                            EmailConfirmed = true,
                            EmployeeBadgeId = "NRL-042",
                            FullName = "Sarah Jenkins",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAH.JENKINS@NRL.CO.IN",
                            NormalizedUserName = "SARAH.JENKINS",
                            PasswordHash = "AQAAAAIAAYagAAAAEKO1RCNoxZOhIUeKzGSiPY3UFB4oMYK8mUbw2Zv8KdYDJQ3MgzHOnPQwEJXjPwtU6A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c88c7e64-d2d1-42e8-ba3a-4ecb4d2858fd",
                            TwoFactorEnabled = false,
                            UserName = "sarah.jenkins"
                        },
                        new
                        {
                            Id = "cccc-cccc-cccc-cccc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "77246e1b-18fc-48ad-ab93-18d64d392499",
                            Department = "IT & Facilities",
                            Email = "marcus.vance@nrl.co.in",
                            EmailConfirmed = true,
                            EmployeeBadgeId = "NRL-108",
                            FullName = "Marcus Vance",
                            LockoutEnabled = false,
                            NormalizedEmail = "MARCUS.VANCE@NRL.CO.IN",
                            NormalizedUserName = "MARCUS.VANCE",
                            PasswordHash = "AQAAAAIAAYagAAAAENYLhZWnG4+Qbgh2uKcnSrvpdqPSRI2RhFzjaZDqrQnLL7c/UOR12TnyIIG49eoOhw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96555fdd-444d-4f6b-b4db-1cf777f6b373",
                            TwoFactorEnabled = false,
                            UserName = "marcus.vance"
                        },
                        new
                        {
                            Id = "dddd-dddd-dddd-dddd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3697af9c-c517-443c-8833-c5923c24ff43",
                            Department = "Catalytic Cracking Unit",
                            Email = "dave.miller@nrl.co.in",
                            EmailConfirmed = true,
                            EmployeeBadgeId = "NRL-504",
                            FullName = "Dave Miller",
                            LockoutEnabled = false,
                            NormalizedEmail = "DAVE.MILLER@NRL.CO.IN",
                            NormalizedUserName = "DAVE.MILLER",
                            PasswordHash = "AQAAAAIAAYagAAAAEHHjLcsF6tse85K/BqztJH0amzaIoVO7iIzoo4fm1NF/Snj0S/m+OamVLXlM+9dFxQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "643ee1ae-5f03-4d9a-ada1-5d7e33c962d2",
                            TwoFactorEnabled = false,
                            UserName = "dave.miller"
                        });
                });

            modelBuilder.Entity("RefineryBooking.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RefineryBooking.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocatorHelpDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ConferenceRoomId")
                        .HasColumnType("int");

                    b.Property<string>("CostCentre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpectedAttendees")
                        .HasColumnType("int");

                    b.Property<string>("ITFMHelpDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MeetingTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("RequiresAllocatorHelp")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresCatering")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresITFMHelp")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ConferenceRoomId", "StartTime", "EndTime", "Status");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RefineryBooking.Models.ConferenceRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("bit");

                    b.Property<bool>("HasVideoConferencing")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWhiteboard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ConferenceRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingLocation = "Admin Block A, Floor 3",
                            Capacity = 24,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "North Gate Boardroom"
                        },
                        new
                        {
                            Id = 2,
                            BuildingLocation = "Plant 2 Operations Center",
                            Capacity = 12,
                            HasProjector = true,
                            HasVideoConferencing = false,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Catalytic Cracker Briefing Room"
                        },
                        new
                        {
                            Id = 3,
                            BuildingLocation = "Visitor Center, Ground Floor",
                            Capacity = 60,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Safety & HAZMAT Training Hall"
                        },
                        new
                        {
                            Id = 4,
                            BuildingLocation = "Technical Services Bldg",
                            Capacity = 8,
                            HasProjector = false,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Pipeline Engineering Hub"
                        },
                        new
                        {
                            Id = 5,
                            BuildingLocation = "HQ Tower, Floor 5",
                            Capacity = 16,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Executive Strategy Suite"
                        },
                        new
                        {
                            Id = 6,
                            BuildingLocation = "Central Control Building",
                            Capacity = 30,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Refinery Operations War Room"
                        },
                        new
                        {
                            Id = 7,
                            BuildingLocation = "Safety Block, Ground Floor",
                            Capacity = 120,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = false,
                            IsActive = true,
                            Name = "HSE Training Auditorium"
                        },
                        new
                        {
                            Id = 8,
                            BuildingLocation = "Maintenance Bldg, Floor 1",
                            Capacity = 20,
                            HasProjector = true,
                            HasVideoConferencing = false,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Turnaround Planning Room"
                        },
                        new
                        {
                            Id = 9,
                            BuildingLocation = "IT Services Block",
                            Capacity = 10,
                            HasProjector = false,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "IT & Instrumentation Lab"
                        },
                        new
                        {
                            Id = 10,
                            BuildingLocation = "Warehouse Block B, Floor 2",
                            Capacity = 14,
                            HasProjector = true,
                            HasVideoConferencing = false,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Logistics & Dispatch Conference Room"
                        });
                });

            modelBuilder.Entity("RefineryBooking.Models.HallBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BlockedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConferenceRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceRoomId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("HallBlocks");
                });

            modelBuilder.Entity("RefineryBooking.Models.ITFacilityRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("MicCount")
                        .HasColumnType("int");

                    b.Property<bool>("NeedsLaptop")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsLaserPointer")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsPASystem")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsProjector")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsVideoConferencing")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsWhiteboard")
                        .HasColumnType("bit");

                    b.Property<int>("SetupStatus")
                        .HasColumnType("int");

                    b.Property<string>("TechNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("ITFacilityRequirements");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RefineryBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RefineryBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RefineryBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RefineryBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RefineryBooking.Models.AllocatorHallAssignment", b =>
                {
                    b.HasOne("RefineryBooking.Models.ApplicationUser", "Allocator")
                        .WithMany()
                        .HasForeignKey("AllocatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RefineryBooking.Models.ConferenceRoom", "ConferenceRoom")
                        .WithMany()
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allocator");

                    b.Navigation("ConferenceRoom");
                });

            modelBuilder.Entity("RefineryBooking.Models.Booking", b =>
                {
                    b.HasOne("RefineryBooking.Models.ConferenceRoom", "ConferenceRoom")
                        .WithMany("Bookings")
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RefineryBooking.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RefineryBooking.Models.HallBlock", b =>
                {
                    b.HasOne("RefineryBooking.Models.ConferenceRoom", "ConferenceRoom")
                        .WithMany()
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RefineryBooking.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConferenceRoom");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("RefineryBooking.Models.ITFacilityRequirement", b =>
                {
                    b.HasOne("RefineryBooking.Models.Booking", "Booking")
                        .WithOne("ITRequirement")
                        .HasForeignKey("RefineryBooking.Models.ITFacilityRequirement", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("RefineryBooking.Models.Booking", b =>
                {
                    b.Navigation("ITRequirement");
                });

            modelBuilder.Entity("RefineryBooking.Models.ConferenceRoom", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
