// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefineryBooking.Data;

#nullable disable

namespace RefineryBooking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729152032_UseWindowsUsernameLogin")]
    partial class UseWindowsUsernameLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            ConcurrencyStamp = "1c1a818f-b5b2-4448-87fc-77d3b1c05d8d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            ConcurrencyStamp = "1ca015da-0b67-4182-b247-57e042e6307f",
                            Name = "Allocator",
                            NormalizedName = "ALLOCATOR"
                        },
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            ConcurrencyStamp = "9c717780-97c8-40ef-b10d-a3fb86e32150",
                            Name = "ITFM",
                            NormalizedName = "ITFM"
                        },
                        new
                        {
                            Id = "44444444-4444-4444-4444-444444444444",
                            ConcurrencyStamp = "0b618b5b-97c8-4b65-82b4-32052adc01dd",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "aaaa-aaaa-aaaa-aaaa",
                            RoleId = "11111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            UserId = "bbbb-bbbb-bbbb-bbbb",
                            RoleId = "22222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            UserId = "cccc-cccc-cccc-cccc",
                            RoleId = "33333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            UserId = "dddd-dddd-dddd-dddd",
                            RoleId = "44444444-4444-4444-4444-444444444444"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RefineryBooking.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeBadgeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "aaaa-aaaa-aaaa-aaaa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "324d44e9-d378-4f8b-8912-6e342b2c2c35",
                            Department = "IT Operations",
                            Email = "admin@nrl.co.in",
                            EmailConfirmed = true,
                            EmployeeBadgeId = "NRL-ADM-001",
                            FullName = "System Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@NRL.CO.IN",
                            NormalizedUserName = "SYS.ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXf143+0bWUjo3wVUorKGMRj0MWZWubZs1AEw2Sk5MvhPZxOy9mPFHSuXSektIg3Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "77244867-1bc2-4535-a999-9000c4964a23",
                            TwoFactorEnabled = false,
                            UserName = "sys.admin"
                        },
                        new
                        {
                            Id = "bbbb-bbbb-bbbb-bbbb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "45228da3-d73d-4de5-b9fb-48f41ec2d056",
                            Department = "Facility Scheduling",
                            Email = "sarah.jenkins@nrl.co.in",
                            EmailConfirmed = true,
                            EmployeeBadgeId = "NRL-042",
                            FullName = "Sarah Jenkins",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAH.JENKINS@NRL.CO.IN",
                            NormalizedUserName = "SARAH.JENKINS",
                            PasswordHash = "AQAAAAIAAYagAAAAEE+8cZuz8J2LqmjBbNYp3jpdqPvR9YfJROO2XWWWPGGzXhnQ+2y/O2gHaUuUJ8vm8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31b0ed54-116d-4e27-a85a-8e53ecc0d807",
                            TwoFactorEnabled = false,
                            UserName = "sarah.jenkins"
                        },
                        new
                        {
                            Id = "cccc-cccc-cccc-cccc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14c46eb9-37dc-4fbc-b21c-a560cc317764",
                            Department = "IT & Facilities",
                            Email = "marcus.vance@nrl.co.in",
                            EmailConfirmed = true,
                            EmployeeBadgeId = "NRL-108",
                            FullName = "Marcus Vance",
                            LockoutEnabled = false,
                            NormalizedEmail = "MARCUS.VANCE@NRL.CO.IN",
                            NormalizedUserName = "MARCUS.VANCE",
                            PasswordHash = "AQAAAAIAAYagAAAAEGq12tyK2v0Ri8/0J2R0V6j+eA5C2le8SU9e+9iHRQCcEl0jJL16VyrxoKuUPvstMw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6477d2bd-191c-4fa4-926d-d3507fe4845a",
                            TwoFactorEnabled = false,
                            UserName = "marcus.vance"
                        },
                        new
                        {
                            Id = "dddd-dddd-dddd-dddd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "130b75a4-4088-493a-b764-1aa80ab3fdc8",
                            Department = "Catalytic Cracking Unit",
                            Email = "dave.miller@nrl.co.in",
                            EmailConfirmed = true,
                            EmployeeBadgeId = "NRL-504",
                            FullName = "Dave Miller",
                            LockoutEnabled = false,
                            NormalizedEmail = "DAVE.MILLER@NRL.CO.IN",
                            NormalizedUserName = "DAVE.MILLER",
                            PasswordHash = "AQAAAAIAAYagAAAAEMOR9UvbC/DEOzWDYs19EqzEfGUmQ7LTEgYwQQcGVIMz4HK8SZNcX1Y7DvDiUYo11Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3e2c93ff-c1f0-4885-8b22-e4e5b31bea8e",
                            TwoFactorEnabled = false,
                            UserName = "dave.miller"
                        });
                });

            modelBuilder.Entity("RefineryBooking.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RefineryBooking.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocatorHelpDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ConferenceRoomId")
                        .HasColumnType("int");

                    b.Property<string>("CostCentre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpectedAttendees")
                        .HasColumnType("int");

                    b.Property<string>("ITFMHelpDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MeetingTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("RequiresAllocatorHelp")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresCatering")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresITFMHelp")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ConferenceRoomId", "StartTime", "EndTime", "Status");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RefineryBooking.Models.ConferenceRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("bit");

                    b.Property<bool>("HasVideoConferencing")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWhiteboard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ConferenceRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingLocation = "Admin Block A, Floor 3",
                            Capacity = 24,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "North Gate Boardroom"
                        },
                        new
                        {
                            Id = 2,
                            BuildingLocation = "Plant 2 Operations Center",
                            Capacity = 12,
                            HasProjector = true,
                            HasVideoConferencing = false,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Catalytic Cracker Briefing Room"
                        },
                        new
                        {
                            Id = 3,
                            BuildingLocation = "Visitor Center, Ground Floor",
                            Capacity = 60,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Safety & HAZMAT Training Hall"
                        },
                        new
                        {
                            Id = 4,
                            BuildingLocation = "Technical Services Bldg",
                            Capacity = 8,
                            HasProjector = false,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Pipeline Engineering Hub"
                        },
                        new
                        {
                            Id = 5,
                            BuildingLocation = "HQ Tower, Floor 5",
                            Capacity = 16,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Executive Strategy Suite"
                        },
                        new
                        {
                            Id = 6,
                            BuildingLocation = "Central Control Building",
                            Capacity = 30,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Refinery Operations War Room"
                        },
                        new
                        {
                            Id = 7,
                            BuildingLocation = "Safety Block, Ground Floor",
                            Capacity = 120,
                            HasProjector = true,
                            HasVideoConferencing = true,
                            HasWhiteboard = false,
                            IsActive = true,
                            Name = "HSE Training Auditorium"
                        },
                        new
                        {
                            Id = 8,
                            BuildingLocation = "Maintenance Bldg, Floor 1",
                            Capacity = 20,
                            HasProjector = true,
                            HasVideoConferencing = false,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Turnaround Planning Room"
                        },
                        new
                        {
                            Id = 9,
                            BuildingLocation = "IT Services Block",
                            Capacity = 10,
                            HasProjector = false,
                            HasVideoConferencing = true,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "IT & Instrumentation Lab"
                        },
                        new
                        {
                            Id = 10,
                            BuildingLocation = "Warehouse Block B, Floor 2",
                            Capacity = 14,
                            HasProjector = true,
                            HasVideoConferencing = false,
                            HasWhiteboard = true,
                            IsActive = true,
                            Name = "Logistics & Dispatch Conference Room"
                        });
                });

            modelBuilder.Entity("RefineryBooking.Models.HallBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BlockedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConferenceRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceRoomId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("HallBlocks");
                });

            modelBuilder.Entity("RefineryBooking.Models.ITFacilityRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("MicCount")
                        .HasColumnType("int");

                    b.Property<bool>("NeedsLaptop")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsLaserPointer")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsPASystem")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsProjector")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsVideoConferencing")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsWhiteboard")
                        .HasColumnType("bit");

                    b.Property<int>("SetupStatus")
                        .HasColumnType("int");

                    b.Property<string>("TechNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("ITFacilityRequirements");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RefineryBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RefineryBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RefineryBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RefineryBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RefineryBooking.Models.Booking", b =>
                {
                    b.HasOne("RefineryBooking.Models.ConferenceRoom", "ConferenceRoom")
                        .WithMany("Bookings")
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RefineryBooking.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RefineryBooking.Models.HallBlock", b =>
                {
                    b.HasOne("RefineryBooking.Models.ConferenceRoom", "ConferenceRoom")
                        .WithMany()
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RefineryBooking.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConferenceRoom");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("RefineryBooking.Models.ITFacilityRequirement", b =>
                {
                    b.HasOne("RefineryBooking.Models.Booking", "Booking")
                        .WithOne("ITRequirement")
                        .HasForeignKey("RefineryBooking.Models.ITFacilityRequirement", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("RefineryBooking.Models.Booking", b =>
                {
                    b.Navigation("ITRequirement");
                });

            modelBuilder.Entity("RefineryBooking.Models.ConferenceRoom", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
